name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn global add @abtnode/cli
      - run: yarn
      - run: yarn bundle
      - uses: blocklet/action-release-to-github@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
